name: Deploy common infrastructure

on:
  push:

permissions:
  contents: read
  id-token: write

jobs:

  get_test_coverage:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Make the test script executable
        run: chmod +x scripts/run_tests.sh

      - name: Run unit and component tests
        run: ./scripts/run_tests.sh --source layers

  build_lambda_layers:

    runs-on: ubuntu-latest
    needs: get_test_coverage
    strategy:
      matrix:
        layers:
          - name: retry_api_exceptions
            path: layers/retry_api_exceptions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Build Lambda layer package
        run: |
          chmod +x ./scripts/build_lambda_layer_package.sh
          ./scripts/build_lambda_layer_package.sh "${{ matrix.layers.name }}" "${{ matrix.layers.path }}"

      - name: Upload Lambda layer zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-layer-${{ matrix.layers.name }}
          path: ${{ matrix.layers.path }}/${{ matrix.layers.name }}.zip

  combine_artifacts:
    runs-on: ubuntu-latest
    needs: build_lambda_layers
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: combined-artifacts

      - name: View files in combined-artifacts directory
        run: ls -la combined-artifacts

      - name: Move ZIPs to combined folder
        run: |
          mkdir combined-zips
          find combined-artifacts -name '*.zip' -exec mv {} combined-zips/ \;

      - name: Upload combined artifact
        uses: actions/upload-artifact@v4
        with:
          name: all-lambdas
          path: combined-zips/

  deploy_infrastructure:

    runs-on: ubuntu-latest
    needs: combine_artifacts
    env:
      S3_STATE_BUCKET_NAME: ${{ secrets.S3_STATE_BUCKET_NAME }}
      TF_VAR_infra_role_arn: ${{ secrets.TF_VAR_INFRA_ROLE_ARN  }}
      TF_VAR_email: ${{ secrets.EMAIL }}
      TF_VAR_environment: "prod"
      TF_VAR_project_name: "accountSetup"
      TF_VAR_aws_region_name: "us-east-2"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Lambda zip artifacts
        uses: actions/download-artifact@v4
        with:
          name: all-lambdas
          path: .

      - name: View files in root directory
        run: ls -la
    
      - name: Set up AWS credentials (using OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.TF_VAR_INFRA_ROLE_ARN }}
          aws-region: 'us-east-2'
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: |
          echo "Initializing Terraform..."
          terraform init \
            -backend-config="bucket=${S3_STATE_BUCKET_NAME}" \
            -backend-config="key=account-setup/terraform.tfstate" \
            -backend-config="region=${TF_VAR_aws_region}" \
            -backend-config="assume_role={role_arn=\"${TF_VAR_infra_role_arn}\", session_name=\"terraform-session\"}"

      - name: Plan Terraform
        run: |
          echo "Planning Terraform configuration..."
          terraform plan -out=tfplan

      - name: Apply Terraform
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Applying Terraform configuration..."
          terraform apply -auto-approve tfplan